version: '3.8'

services:
  db:
    image: postgres:15
    container_name: b2b_credit_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: b2b_credit_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d b2b_credit_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:
